### ISSUE TITLE
(Player Moved Wrongly!) Ability to change the moved-wrongly-threshold

### ISSUE THREAD

**Issue by Razorskills** [MinecraftPortCentral/Cauldron-Issues#151]
moved-wrongly-threshold
Default: 0.0625
Type: Decimal
Description: Controls the threshold for the "moved wrongly" check. Increasing this number may reduce the amount of rubber-banding on the server but could potentially be abused by players as well.

This is a thing from spigot: http://www.spigotmc.org/wiki/spigot-configuration-spigot-yml/#main-ungrouped-settings

and I believe the new build of cauldron have pulled this into it, and I cannot find a way to change the setting in cauldron.. (Specifically because we use Smart Moving on our server, it allows the player to move just a bit faster than vanilla. Enough so that (I think this^) is catching it and making the player rubber band back to where the server thinks the player should be. It is a verry annoying problem making multiplayer a terrible experience. It also affects other mods like: ic2 Quantum suit.

Hopefully whoever is updating cauldron to newest forge builds could add in this ability.

**Comment by Razorskills** [comment]
ah I think i found out how to do it properly in case anyone else was interested:

```
settings:
  player-shuffle: 0
  bungeecord: false
  late-bind: false
  sample-count: 12
  timeout-time: 90
  restart-on-crash: true
  restart-script: ./start.sh
  netty-threads: 4
  moved-wrongly-threshold: 1.0625
```

I added the "moved-wrongly-threshold: 1.0625" in the settings section of the spigot.yml config.

I decided to launch an actual spigot server, then go to the config and find the settings I wanted and copied them over. I guess cauldron just doesn't generate all of the configs that are available. Maybe that could be something to be fixed. but most people wont have this problem, so oh well.

But my case is closed.
