### ISSUE TITLE
PEX groups not working correctly

### ISSUE THREAD

**Issue by Twisted-Code** [MinecraftPortCentral/Cauldron-Issues#66]
Not sure whose side of the fence this is on, so I will post it both here and in PEX's dev.bukkit forums:
after launching the latest version of PEX (1.6), creating a group, and setting the "prefix" option for the group, I tested it by putting myself in the group and saying something. When that failed, I reloaded PEX but it still didn't work.

``` YAML
groups:
  default:
    options:
      default: true
    permissions:
    - modifyworld.*
  Owner:
    permissions:
    - permissions.*
    options:
      prefix: (owner)
  Admin:
    permissions: []
schema-version: 1
users:
  768df022-edbe-43df-b007-0aba07ed03b7:
    permissions:
    - permissions.*
    options:
      name: macks2008
    group:
    - Owner
```
